Repository EmbeddedRPC/erpc, pull requests merged in 2020-10, with the labels that each got.

#131 Added pre post cb functions for erpc calls.
  erpc_c/config/erpc_config.h
  erpc_c/infra/erpc_client_manager.h
  erpc_c/infra/erpc_client_server_common.h
  erpc_c/infra/erpc_pre_post_action.cpp
  erpc_c/infra/erpc_pre_post_action.h
  erpc_c/infra/erpc_server.h
  erpc_c/infra/erpc_simple_server.cpp
  erpc_c/port/erpc_config_internal.h
  erpc_c/port/erpc_setup_extensions.h
  erpc_c/port/erpc_setup_extensions_freertos.cpp
  erpc_c/port/erpc_threading.h
  erpc_c/setup/erpc_arbitrated_client_setup.cpp
  erpc_c/setup/erpc_arbitrated_client_setup.h
  erpc_c/setup/erpc_client_setup.cpp
  erpc_c/setup/erpc_client_setup.h
  erpc_c/setup/erpc_server_setup.cpp
  erpc_c/setup/erpc_server_setup.h
  erpcgen/src/templates/c_client_source.template
Labels: enhancement

#137 matrix_multiply.py: Add --serial and --baud argument
  examples/matrix_multiply_tcp_python/matrix_multiply.py
Labels: enhancement

#136 Paranoid compiler flags -Wall -Wextra -Wshadow -pedantic-errors
  erpc_c/infra/erpc_arbitrated_client_manager.h
  erpc_c/infra/erpc_client_manager.h
  erpc_c/infra/erpc_transport.h
  erpc_c/port/erpc_port.h
  erpc_c/port/erpc_port_stdlib.cpp
  erpc_c/port/erpc_serial.cpp
  erpc_c/port/erpc_threading_pthreads.cpp
  erpc_c/transports/erpc_tcp_transport.cpp
  erpcgen/src/AstWalker.h
  erpcgen/src/CGenerator.cpp
  erpcgen/src/ErpcLexer.h
  erpcgen/src/Generator.cpp
  erpcgen/src/Generator.h
  erpcgen/src/InterfaceDefinition.cpp
  erpcgen/src/PythonGenerator.cpp
  erpcgen/src/SearchPath.cpp
  erpcgen/src/SymbolScanner.cpp
  erpcgen/src/UniqueIdChecker.cpp
  erpcgen/src/cpptemplate/Makefile
  erpcgen/src/cpptemplate/cpptempl.cpp
  erpcgen/src/erpcgen.cpp
  erpcgen/src/erpcgen_lexer.l
  erpcgen/src/erpcgen_parser.y
  erpcgen/src/options.cpp
  erpcgen/src/types/Function.h
  erpcgen/src/types/Type.cpp
  erpcsniffer/src/Sniffer.cpp
  erpcsniffer/src/erpcsniffer.cpp
  mk/flags.mk
  test/common/gtest/gtest.cpp
  test/common/gtest/gtest.h
  test/common/unit_test_serial_client.cpp
  test/common/unit_test_tcp_client.cpp
  test/test_annotations/test_annotations_client_impl.cpp
Labels: enhancement

#125 add ustring builtin type (unsigned char*)
  erpcgen/src/CGenerator.cpp
  erpcgen/src/InterfaceDefinition.cpp
  erpcgen/src/templates/c_coders.template
  erpcgen/src/types/BuiltinType.h
  erpcgen/src/types/DataType.h
Labels: enhancement

#139 paranoid-2: Allow to compile code with paranoid compiler flags -Wall -Wextra -Wshadow -Werror -pedantic-errors
  erpc_c/infra/erpc_simple_server.cpp
Labels: enhancement

#121 deadlock fix proposals
  erpc_c/infra/erpc_manually_constructed.h
  erpc_c/infra/erpc_transport_arbitrator.cpp
  erpc_c/port/erpc_threading_freertos.cpp
  erpc_c/setup/erpc_setup_tcp.cpp
  erpc_c/setup/erpc_transport_setup.h
  erpc_c/transports/erpc_tcp_transport.cpp
  erpc_c/transports/erpc_tcp_transport.h
Labels: bug, enhancement

#140 AllowShortFunctionsOnASingleLine was twice.
  .clang-format
Labels: bug

#141 erpc_framed_transport.cpp: return error if received message has zero length
  erpc_c/infra/erpc_framed_transport.cpp
Labels: enhancement
