Repository EmbeddedRPC/erpc, pull requests merged in 2022-01, with the labels that each got.

#220 construct the USB CDC transport, rather than a client
  erpc_c/setup/erpc_setup_usb_cdc.cpp
Labels: bug

#206 Fix syntax errors in Python erpcgen ouput
  erpcgen/src/templates/py_common.template
Labels: bug

#224 Improved test for union
  erpcgen/test/test_union_py.yml
Labels: bug

#38 Updated erpc_python/setup.py
  erpc_python/setup.py
Labels: bug, enhancement

#226 [38] Fixing error in erpc setup command: use_2to3 is invalid.
  erpc_python/setup.py
Labels: bug

#225 Improve python detection
  mk/paths.mk
Labels: enhancement

#227 Fix several warnings with deprecated call in pytest
  erpc_c/infra/erpc_basic_codec.cpp
  erpcgen/test/conftest.py
Labels: enhancement

#228 Fixed freeing union members when only default need be freed.
  erpcgen/src/CGenerator.cpp
  erpcgen/src/templates/c_coders.template
  erpcgen/src/templates/c_common_functions.template
  erpcgen/test/test_union_c.yml
Labels: bug

#229 Fixed making test under Linux
  erpc_c/port/erpc_config_internal.h
  erpcgen/src/templates/c_server_header.template
  erpcgen/src/templates/c_server_source.template
  erpcgen/test/test_dynamic_ann_c.yml
  erpcgen/test/test_service_c.yml
  test/common/config/erpc_config.h
  test/test_arbitrator/config/erpc_config.h
  test/test_arrays/test_arrays_server_impl.cpp
  test/test_binary/test_binary_server_impl.cpp
  test/test_builtin/test_builtin_server_impl.cpp
  test/test_callbacks/test_callbacks_server_impl.cpp
  test/test_const/test_const_server_impl.cpp
  test/test_enums/test_enums_server_impl.cpp
  test/test_lists/test_lists_server_impl.cpp
  test/test_shared/test_shared_server_impl.cpp
  test/test_struct/test_struct_server_impl.cpp
  test/test_typedef/test_typedef_server_impl.cpp
  test/test_unions/test_unions_server_impl.cpp
Labels: bug

#148 PR to issue #143: Assert costumizing
  erpc_c/config/erpc_config.h
  erpc_c/infra/erpc_arbitrated_client_manager.cpp
  erpc_c/infra/erpc_basic_codec.cpp
  erpc_c/infra/erpc_client_manager.cpp
  erpc_c/infra/erpc_framed_transport.cpp
  erpc_c/infra/erpc_message_buffer.cpp
  erpc_c/infra/erpc_server.cpp
  erpc_c/infra/erpc_transport_arbitrator.cpp
  erpc_c/port/erpc_config_internal.h
  erpc_c/port/erpc_setup_extensions_freertos.cpp
  erpc_c/port/erpc_threading_freertos.cpp
  erpc_c/port/erpc_threading_mbed.cpp
  erpc_c/port/erpc_threading_threadx.cpp
  erpc_c/port/erpc_threading_zephyr.cpp
  erpc_c/setup/erpc_arbitrated_client_setup.cpp
  erpc_c/setup/erpc_client_setup.cpp
  erpc_c/setup/erpc_server_setup.cpp
  erpc_c/setup/erpc_setup_mbf_dynamic.cpp
  erpc_c/setup/erpc_setup_mbf_rpmsg.cpp
  erpc_c/setup/erpc_setup_mbf_rpmsg_tty.cpp
  erpc_c/setup/erpc_setup_mbf_static.cpp
  erpc_c/transports/erpc_inter_thread_buffer_transport.cpp
  erpc_c/transports/erpc_rpmsg_linux_transport.cpp
  erpc_c/transports/erpc_rpmsg_lite_rtos_transport.cpp
  erpc_c/transports/erpc_rpmsg_tty_rtos_transport.cpp
  erpcsniffer/src/erpc_config.h
  test/common/config/erpc_config.h
  test/common/unit_test_serial_client.cpp
  test/common/unit_test_serial_server.cpp
  test/common/unit_test_tcp_arbitrator_client.cpp
  test/common/unit_test_tcp_arbitrator_server.cpp
  test/common/unit_test_tcp_client.cpp
  test/common/unit_test_tcp_server.cpp
  test/test_arbitrator/config/erpc_config.h
Labels: enhancement
