Repository EmbeddedRPC/erpc, pull requests merged in 2023-09, with the labels that each got.

#376 Change mac build target from deprecated to new
  .circleci/config.yml
Labels: bug, enhancement

#377 Change mac build target from deprecated to temporary
  .circleci/config.yml
Labels: bug, enhancement

#373 Fixed rpmsg tty transport to work with serial transport
  erpc_c/transports/erpc_rpmsg_tty_rtos_transport.cpp
Labels: bug

#365 Feature/winsock2 support
  .circleci/config.yml
  erpc_c/Makefile
  erpc_c/port/erpc_config_internal.h
  erpc_c/port/erpc_port_stdlib.cpp
  erpc_c/setup/erpc_arbitrated_client_setup.cpp
  erpc_c/setup/erpc_client_setup.cpp
  erpc_c/transports/erpc_tcp_transport.cpp
  erpc_c/transports/erpc_tcp_transport.hpp
  erpcgen/src/templates/c_common_functions.template
  mk/common.mk
  mk/flags.mk
  mk/targets.mk
  test/common/gtest/gtest.cpp
  test/mk/erpc_src.mk
  test/mk/test.mk
  test/mk/unit_test.mk
  test/run_unit_tests.py
Labels: enhancement
